### ISSUE TITLE
why the prediction value of all images were same?

### ISSUE THREAD

**Issue by ShuLongShiWo** [alex-myzhao/vgg#1]
when i do the test, i got all test prediction value:
2008_000019.jpg
[[  4.04371026e-09   3.77670117e-09   4.59400740e-09   4.59508520e-09
    5.49547652e-09   4.16764934e-09   2.97392209e-08   9.73618608e-09
    8.25396818e-09   4.37411174e-09   4.23366764e-09   1.99124965e-08
    5.81169157e-09   3.72128484e-09   1.00000000e+00   5.23175192e-09
    4.69186867e-09   5.50169599e-09   4.52404381e-09   4.61029082e-09]]
2008_000023.jpg
[[  4.04371026e-09   3.77670117e-09   4.59400740e-09   4.59508520e-09
    5.49547652e-09   4.16764934e-09   2.97392209e-08   9.73618608e-09
    8.25396818e-09   4.37411174e-09   4.23366764e-09   1.99124965e-08
    5.81169157e-09   3.72128484e-09   1.00000000e+00   5.23175192e-09
    4.69186867e-09   5.50169599e-09   4.52404381e-09   4.61029082e-09]]
2008_000028.jpg
[[  4.04371026e-09   3.77670117e-09   4.59400740e-09   4.59508520e-09
    5.49547652e-09   4.16764934e-09   2.97392209e-08   9.73618608e-09
    8.25396818e-09   4.37411174e-09   4.23366764e-09   1.99124965e-08
    5.81169157e-09   3.72128484e-09   1.00000000e+00   5.23175192e-09
    4.69186867e-09   5.50169599e-09   4.52404381e-09   4.61029082e-09]]

all images have the same prediction value, but it's very strange. who can tell me why?

**Comment by mark-myzhao** [comment]
Hi, @ShuLongShiWo 
I have experienced this problem when I was trying to train a VGG net **with randomly initializing**.
And I strongly suggest that you can try to **fine tune this model with pre-trained VGG model** , which can be searched on Github, on this Dataset.

**Comment by ShuLongShiWo** [comment]
ok, thanks very much
